Blog app - controllers specs
Feliverse/Blog-App-Feliverse pull request #6
Opened 2023-05-16 21:30 UTC by Feliverse

### Project requirements

- Add RSpec as a gem to your project.
- Create a Request spec file for all your controllers.
- Make sure that for each action you check:

> If response status was correct.
> If a correct template was rendered.
> If the response body includes correct placeholder text.

2023-05-17 02:23 UTC, Davidosky007 requested changes
Hi @Feliverse 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* Well written PR 👍 
* Tests written for controllers 👍 

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-17 02:23 UTC, Davidosky007 commented on spec/requests/posts_spec.rb
> +    end
* I get this errors when i run test , kindly fix it 
![image](https://github.com/Feliverse/Blog-App-Feliverse/assets/52497246/cb3553b1-1e99-4bd6-8730-f0186408aa0b)

2023-05-17 17:56 UTC, vickymarz requested changes
Hi @Feliverse, 

Great work on making the changes requested by a previous reviewer 👏 🔥 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://camo.githubusercontent.com/56bcd754643682fcc078b66eaa7278dead6c9c5013595c875b4ddcbe0f0ef0aa/68747470733a2f2f6d65646961302e67697068792e636f6d2f6d656469612f78554f786668365a4d373565664d3342716f2f67697068792d646f776e73697a65642d6d656469756d2e676966)

## Top highlight 🎯

- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


 ## Required Changes ♻️

- [ ] Your tests are still failing. Could you fix your test cases? I think you should check out your tests properly and ensure they are well-written.
![image](https://github.com/Feliverse/Blog-App-Feliverse/assets/63473584/c2306088-97d9-448f-8dbd-eca7171d5cf4)


_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 14:16 UTC, Feliverse commented
Hi @vickymarz , I fix my databases configuration to test, now all is working good.
Thanks for your PR and the Zoom call.

2023-05-18 14:45 UTC, Gambit142 approved these changes
Hi @Feliverse 👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights
- All linters checks passed ✔️ 
- All controller tests are located in the `request` directory ✔️
- Wrote tests for **_User and Post index and show_** pages ✔️

### Optional Suggestions
- Kindly consider the comments tagged _**[OPTIONAL]**_ under this review summary 👍   

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-05-18 14:45 UTC, Gambit142 commented on spec/post_spec.rb
>      post.valid?
- [OPTIONAL] Great work making all the tests in the `requests` directory pass. It would be nice to delete those test files that are outside the `requests` directory as they are not part of this requirement and they are all failing. I guess they were created when you used one of the rails generators to create models. Kindly remove them. 👍

2023-05-18 16:39 UTC, Feliverse commented on spec/post_spec.rb
>      post.valid?
Nice suggestion, I will delete that specs

2023-05-18 16:39 UTC, merged

2023-05-18 20:55 UTC, Gambit142 commented on spec/post_spec.rb
>      post.valid?
@Feliverse, alright. It would make the project better I believe.